### PR TITLE
Fix warnings in sphinx document generation

### LINKED ISSUE #252: Build problem: WARNING: unknown option: mydumper --schemas
Hi all,

when building mydumper (sorce from git), we can see this error 
```
...
[ 91%] Building HTML documentation with Sphinx
/export/home/3eka/tmp/SFW_build/mydumper/bld/docs/_sources/files.rst:39: WARNING: unknown option: mydumper --schemas
WARNING: html_static_path entry '/export/home/3eka/tmp/SFW_build/mydumper/docs/_static' does not exist
[ 91%] Built target doc_html
...
```
Regards.

### PR DESCRIPTION
**Pull request by fredricj**
Fix warnings in sphinx document generation caused by non-existing directories and removed options
Fixes #252

### CODE REVIEW

**Review by davidducos — CHANGES_REQUESTED** [review]
I confirmed the warnings:
```
[ 91%] Building HTML documentation with Sphinx
/tmp/mydumpertmp/mydumper/docs/_sources/files.rst:39: WARNING: unknown option: mydumper --schemas
WARNING: html_static_path entry '/tmp/mydumpertmp/mydumper/docs/_static' does not exist
```
But I don't think that we need to comment this line:
`html_static_path = ['@CMAKE_CURRENT_SOURCE_DIR@/_static']
`
we should change it to:
`html_static_path = ['@CMAKE_CURRENT_SOURCE_DIR@/html/_static']`

**Review by davidducos — APPROVED** [review]

**Comment by fredricj** [comment]
The change to html_static_path still causes warning on both initial build and a different warning on 2nd run without a clean in between. Since there is no extra static files the html_static_path should not be used AFAIU.

**Comment by davidducos** [comment]
Hi @fredricj 
Thanks for checking! I'm not seeing any error on focal, what OS are you testing?

**Comment by fredricj** [comment]
It gives the warning on centos7 but not on centos8

**Comment by davidducos** [comment]
Hi @fredricj,
Thanks for checking! I can't reproduce your scenario:
```
[root@localhost mydumper]# cmake .
-- Using mysql-config: /bin/mysql_config
-- Found MySQL: /usr/include/mysql, /usr/lib64/mysql/libmysqlclient.so;/usr/lib64/libpthread.so;/usr/lib64/libz.so;/usr/lib64/libm.so;/usr/lib64/librt.so;/usr/lib/libcoredumper.a;/usr/lib64/libssl.so;/usr/lib64/libcrypto.so;/usr/lib64/libdl.so
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Found PkgConfig: /bin/pkg-config (found version "0.27.1")
-- checking for one of the modules 'glib-2.0'
-- checking for one of the modules 'gthread-2.0'
-- checking for one of the modules 'gio-2.0'
-- checking for one of the modules 'gobject-2.0'
-- checking for module 'libpcre'
--   found libpcre, version 8.32
-- Found PCRE: /usr/include

CMake Warning at docs/CMakeLists.txt:9 (message):
  Unable to find Sphinx documentation generator


-- ------------------------------------------------
-- MYSQL_CONFIG = /bin/mysql_config
-- CMAKE_INSTALL_PREFIX = /usr/local
-- BUILD_DOCS = ON
-- WITH_BINLOG = OFF
-- RUN_CPPCHECK = OFF
-- Change a values with: cmake -D<Variable>=<Value>
-- ------------------------------------------------
--
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/mydumper
[root@localhost mydumper]# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)
```
Do you see any difference in our tests?

**Comment by fredricj** [comment]
> CMake Warning at docs/CMakeLists.txt:9 (message):
>   Unable to find Sphinx documentation generator
> 
> Do you see any difference in our tests?

You don't have python-sphinx or python3-sphinx installed

**Comment by davidducos** [comment]
@fredricj, sorry, my mistake! here is the right log:
```
[root@localhost mydumper]# rpm -qa | grep python-sph
python-sphinx-1.1.3-11.el7.noarch
[root@localhost mydumper]# cmake .
-- Using mysql-config: /bin/mysql_config
-- Found MySQL: /usr/include/mysql, /usr/lib64/mysql/libmysqlclient.so;/usr/lib64/libpthread.so;/usr/lib64/libz.so;/usr/lib64/libm.so;/usr/lib64/librt.so;/usr/lib/libcoredumper.a;/usr/lib64/libssl.so;/usr/lib64/libcrypto.so;/usr/lib64/libdl.so
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Found PkgConfig: /bin/pkg-config (found version "0.27.1")
-- checking for one of the modules 'glib-2.0'
-- checking for one of the modules 'gthread-2.0'
-- checking for one of the modules 'gio-2.0'
-- checking for one of the modules 'gobject-2.0'
-- checking for module 'libpcre'
--   found libpcre, version 8.32
-- Found PCRE: /usr/include
1
-- ------------------------------------------------
-- MYSQL_CONFIG = /bin/mysql_config
-- CMAKE_INSTALL_PREFIX = /usr/local
-- BUILD_DOCS = ON
-- WITH_BINLOG = OFF
-- RUN_CPPCHECK = OFF
-- Change a values with: cmake -D<Variable>=<Value>
-- ------------------------------------------------
--
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/mydumper
```
No warning...

**Comment by fredricj** [comment]
The warning occurs during build, not when configuring.

**Comment by davidducos** [comment]
I can see the issue now...

**Pull request merged**
