### PR TITLE
Added support for dumping checksums

### PR DESCRIPTION
**Pull request by stephenreay**
This is an initial change to provide the functionality requested in #141 

As mentioned in the issue - this isn't my normal gig, I'm just trying to solve a problem.

### CODE REVIEW

**Comment by stefanhipfel** [comment]
This is something I also need for my backup scenario. This is the perfect place to get accurate checksums of tables at the moment of backup while the lock is still active!

**Comment by stephenreay** [comment]
@maxbube any chance you can take a look at this soon?

@stefanhipfel haven’t found another reliable solution, sorry.

**Comment by stephenreay** [comment]
Bump. @maxbube any chance you could look at this?

**Comment by stephenreay** [comment]
@maxbube is there something I can do, to improve this, so it can be accepted?

**Comment by davidducos** [comment]
Hi @stephenreay,

I reviewed it and if I didn't understood this incorrectly, you want the checksums to check the consistency of the backup after restore. However, I don't see any change in myloader to perform the checksum analysis. If you can add a commit with myloader support, I will be reviewing and adding suggestions. 

Thanks!

**Comment by stephenreay** [comment]
@davidducos thanks for looking at this!

I didn't add loader support at the time as I was hoping for some feedback on the change to dumper (C is not my usual bread and butter language). It also seemed slightly less crucial - getting the checksum inside the transaction is essential - but in the case of a restore it's likely that no ongoing operations are running queries so it's more feasible to run a manual query after restore to compare the checksum.

However, I will endeavour to add checking support in loader. Thanks again for looking at this!

**Comment by stephenreay** [comment]
@davidducos I've rebased the branch and added support for verifying checksums after loading.

It doesn't try to use the worker threads for verification, as a data load could still be in-progress on another thread. 

I'm all ears for feedback on how this might be improved.


Thanks again for looking at this!

**Comment by davidducos** [comment]
@stephenreay I have several changes on my bucket but I don't have permissions to pull on your repository. Is it possible to grant my user (@davidducos) the privileges to commit on your repo/branch?

**Comment by stephenreay** [comment]
@davidducos done. Sorry for the delay. Thanks!

**Comment by davidducos** [comment]
@stephenreay I did a couple of changes, please, review to confirm that it is working as expected. Take into account that I change the variable name to dump_checksum and that the default is going to be FALSE by default, as it will be a negative impact in performance if it is enable. Please, let me know your thoughts.

**Comment by stephenreay** [comment]
Hey @davidducos it seems to work fine still.

I swapped the help text, and I had to change the short-option, because it was conflicting with `-U, --updated-since`.
I picked `-M` just because it was the next available letter in the word checksum, but I don't think it's a big deal if it only had a long option name, either.

**Review by davidducos — APPROVED** [review]

**Pull request merged**
